# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Just notes from Opie
tagline:             'A commentary on AutoCAD and Civil 3d'
description:         'A little commentary on my work customizing AutoCAD and Civil 3d to create pretty pictures for construction, by <a href="https://twitter.com/justopie" target="_blank">@justopie</a>.'
url:                 http://justopie.github.io
baseurl:             /
paginate:            5

excerpt_separator: <!--more-->

# About/contact
author:
  name:              Richard Lawrence
  url:               https://twitter.com/Justopie
  email:             Justopie@gmail.com

# Custom vars
version:             1.0.0
