# Dependencies
markdown:            redcarpet
highlighter:         pygments

redcarpet:
  extensions: [autolink]

exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]

timezone:            USA/Chicago

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Just notes from Opie
tagline:             'A commentary on AutoCAD and Civil 3d'
description:         'A little commentary on my work customizing AutoCAD and Civil 3d to create pretty pictures for construction, by <a href="https://twitter.com/justopie" target="_blank">@justopie</a>.'
url:                 http://justopie.github.io
baseurl:             /
paginate:            5

# excerpt_separator: <!--more-->

# About/contact
authors:
  opie:
    name:    Richard Lawrence
	url:     https://justopie.github.io
	twitter: JustOpie
	github:  justopie
	email:   JustOpie@gmail.com
	web:     https://justopie.github.io

# Custom vars
version:             1.0.0
