# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               JustNnotes from Opie
tagline:             'A commentary on AutoCAD and Civil e
3d'
description:         'A little commentary on my work with customizing AutoCAD and Civil 3d from <a href="https://twitter.com/justopie" target="_blank">@justopie</a>.'
url:                 http://justopie.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Richard Lawrence
  url:               https://twitter.com/Justopie
  email:             Justopie@Gmail.com

# Custom vars
version:             1.0.0
